# Generated by Django 5.2.2 on 2025-06-08 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_code', models.CharField(help_text='Identifiant unique du client', max_length=20, primary_key=True, serialize=False, verbose_name='Code client')),
                ('nom', models.CharField(max_length=100, verbose_name='Raison sociale')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_tel', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('fournisseur_code', models.CharField(help_text='Identifiant unique du fournisseur', max_length=20, primary_key=True, serialize=False, verbose_name='Code fournisseur')),
                ('nom', models.CharField(max_length=100, verbose_name='Raison sociale')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_tel', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('lot_code', models.CharField(help_text="Identifiant unique du lot, ex. 'Lot#124'", max_length=20, primary_key=True, serialize=False, verbose_name='Code du lot')),
                ('date_production', models.DateField(verbose_name='Date de production')),
                ('quantite_kg', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantité produite (kg)')),
                ('type_plastique', models.CharField(choices=[('PET', 'PET'), ('PVC', 'PVC'), ('PEHD', 'PEHD')], max_length=10, verbose_name='Type de plastique')),
                ('machine', models.CharField(max_length=100, verbose_name='Machine utilisée')),
            ],
            options={
                'verbose_name': 'Lot de production',
                'verbose_name_plural': 'Lots de production',
                'ordering': ['-date_production'],
            },
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('achat_code', models.CharField(help_text="Identifiant unique de l'achat", max_length=20, primary_key=True, serialize=False, verbose_name='Code achat')),
                ('type_matiere', models.CharField(choices=[('resine_pet', 'Résine PET'), ('additif', 'Additif')], max_length=20, verbose_name='Type de matière')),
                ('quantite_achetee_kg', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantité achetée (kg)')),
                ('cout_unitaire_eur', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Coût unitaire (€ / kg)')),
                ('date_achat', models.DateField(verbose_name="Date d'achat")),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats', to='GestionPlast.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
                'ordering': ['-date_achat'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('numero', models.CharField(help_text='Identifiant unique de la commande', max_length=50, primary_key=True, serialize=False, verbose_name='Numéro de commande')),
                ('date_commande', models.DateField(verbose_name='Date de commande')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('livree', 'Livrée'), ('annulee', 'Annulée')], max_length=20, verbose_name='Statut')),
                ('quantite_vendue_kg', models.DecimalField(decimal_places=3, help_text='Quantité prélevée sur le lot', max_digits=10, verbose_name='Quantité vendue (kg)')),
                ('prix_unitaire_eur', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Prix unitaire (€ / kg)')),
                ('date_livraison', models.DateField(verbose_name='Date de livraison')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='GestionPlast.client', verbose_name='Client')),
                ('lot', models.ForeignKey(help_text="Sélectionnez le code du lot (jusqu'à la quantité disponible)", on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='GestionPlast.production', verbose_name='Lot commandé')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='Qualite',
            fields=[
                ('test_code', models.CharField(help_text='Identifiant unique du test qualité', max_length=20, primary_key=True, serialize=False, verbose_name='Code du test')),
                ('taux_defauts_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux de défauts (%)')),
                ('type_test', models.CharField(choices=[('resistance', 'Résistance mécanique'), ('transparence', 'Transparence optique')], max_length=20, verbose_name='Type de test')),
                ('resultat', models.CharField(choices=[('conforme', 'Conforme'), ('non_conforme', 'Non conforme')], max_length=20, verbose_name='Résultat du test')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('lot', models.ForeignKey(help_text='Sélectionnez le code du lot de production', on_delete=django.db.models.deletion.CASCADE, related_name='tests_qualite', to='GestionPlast.production', verbose_name='Lot de production')),
            ],
            options={
                'verbose_name': 'Test qualité',
                'verbose_name_plural': 'Tests qualité',
            },
        ),
    ]
