# Generated by Django 5.2.2 on 2025-06-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPlast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('code', models.CharField(help_text='Identifiant unique de la machine', max_length=20, primary_key=True, serialize=False, verbose_name='Code machine')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la machine')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
            },
        ),
        migrations.RemoveField(
            model_name='production',
            name='machine',
        ),
        migrations.AddField(
            model_name='production',
            name='machines',
            field=models.ManyToManyField(help_text='Sélectionnez les machines ayant participé à la production', related_name='productions', to='GestionPlast.machine', verbose_name='Machines utilisées'),
        ),
    ]
